<?php

namespace Dywee\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findForFooter($limit = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.state = 1')
            ->orderBy('a.publicationDate', 'desc');

        if(is_numeric($limit))
            $qb->setMaxResults(5);

        $query = $qb->getQuery();

        return $query->getArrayResult();
    }
}
