<?php

namespace Dywee\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTagRepository extends EntityRepository
{
}
